### ISSUE TITLE
Having trouble to run 

### ISSUE THREAD

**Issue by alecinvan** [otoolep/stormkafkamon#7]
Hi, 

I clone this package, do install, and seems to be good, and like to run the command similar to example, but fails like

root@DO-mq-dev:/home/stuser/stormkafkamon/stormkafkamon# ./monitor.py
Traceback (most recent call last):
  File "./monitor.py", line 10, in <module>
    from processor import process, ProcessorError
  File "/home/stuser/stormkafkamon/stormkafkamon/processor.py", line 15, in <module>
    from kafka.client import KafkaClient, OffsetRequest
ImportError: cannot import name OffsetRequest

Any idea?

thanks

**Comment by otoolep** [comment]
You must have this installed on your system first before attempting to run the tool:

https://github.com/mumrah/kafka-python/tree/0.7

**Comment by ecamaj** [comment]
Installed, but still...?

root@0cbe4f4d0e62:/usr/src/myapp/stormkafkamon# pip list
kafka-python (1.0.3.dev0)
kazoo (1.0)
pip (8.1.1)
prettytable (0.7.2)
requests (2.9.1)
setuptools (20.3.1)
simplejson (3.8.2)
six (1.10.0)
stormkafkamon (0.1.0)
virtualenv (15.0.1)
wheel (0.29.0)
zope.interface (4.1.3)

root@0cbe4f4d0e62:/usr/src/myapp/stormkafkamon# python monitor.py --zserver tbdcnt1:2181 --topology FM --spoutroot readKafka --friendly
Traceback (most recent call last):
  File "monitor.py", line 10, in <module>
    from processor import process, ProcessorError
  File "/usr/src/myapp/stormkafkamon/processor.py", line 15, in <module>
    from kafka.client import KafkaClient, OffsetRequest
ImportError: cannot import name OffsetRequest

**Comment by otoolep** [comment]
What version of Kafka are you running? This tool only supports Kafka 0.7 and Storm 0.82.

**Comment by otoolep** [comment]
Also, I don't know if the libraries this tool uses has changed too much. stormkafkamon may need updates.
